// GENERATED by zenstack-mcp — do not edit manually
// Re-run: zenstack generate
import type { McpConfig } from 'zenstack-mcp'

export const mcpConfig: McpConfig = {
  models: {
    "User": { exposed: true },
    "Post": { exposed: true, limit: 10 }
  }
}
