import type { CliGeneratorContext } from '@zenstackhq/sdk'
import { ModelUtils } from '@zenstackhq/sdk'
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

// Match AST nodes by their `$type` discriminant instead of importing the
// `isDataModel`/`isProcedure` guards from `@zenstackhq/language/ast`. Those
// guards pull in the language package's langium-based reflection, which the
// bundler inlines — and that inlined copy breaks when the host ZenStack ships
// a different major of langium (e.g. 3.x → 4.x rewrote AbstractAstReflection).
// `DataModel` and `Procedure` are concrete leaf node types, so a `$type`
// equality check is exactly equivalent to the reflection-based guards.
const isDataModel = (d: { $type: string }) => d.$type === 'DataModel'
const isProcedure = (d: { $type: string }) => d.$type === 'Procedure'

export async function generate(context: CliGeneratorContext): Promise<void> {
  const { model, defaultOutputPath, pluginOptions } = context
  const outputDir = (pluginOptions.output as string | undefined) ?? defaultOutputPath
  const globalExpose = (pluginOptions.expose as boolean | undefined) ?? true

  const dataModels = model.declarations.filter(isDataModel)

  const modelEntries: string[] = dataModels.map((dm) => {
    const mcpAttr = ModelUtils.getAttribute(dm, '@@mcp')
    let exposed: boolean

    if (mcpAttr) {
      const arg = mcpAttr.args?.[0]
      // Default arg (expose) — if present check its value, else default to true
      if (arg?.value?.$type === 'BooleanLiteral') {
        exposed = (arg.value as { value: boolean }).value
      } else {
        exposed = true
      }
    } else {
      exposed = globalExpose
    }

    return `    ${JSON.stringify(dm.name)}: { exposed: ${exposed} }`
  })

  // Custom procedures (`procedure` / `mutation procedure`). Exposed per the
  // global `expose` plugin option (default true). Fine-grained per-procedure
  // gating can be done by editing the generated mcpConfig.procedures map.
  const procedures = model.declarations.filter(isProcedure)
  const procedureEntries: string[] = procedures.map(
    (proc) => `    ${JSON.stringify(proc.name)}: { exposed: ${globalExpose} }`,
  )

  const proceduresBlock = procedureEntries.length
    ? `,\n  procedures: {\n${procedureEntries.join(',\n')}\n  }`
    : ''

  const code = `// GENERATED by zenstack-mcp — do not edit manually
// Re-run: zenstack generate
import type { McpConfig } from 'zenstack-mcp'

export const mcpConfig: McpConfig = {
  models: {
${modelEntries.join(',\n')}
  }${proceduresBlock}
}
`

  mkdirSync(outputDir, { recursive: true })
  writeFileSync(join(outputDir, 'mcp-config.ts'), code, 'utf8')
}
