import type { CliGeneratorContext } from '@zenstackhq/sdk'
import { ModelUtils } from '@zenstackhq/sdk'
import { isDataModel } from '@zenstackhq/language/ast'
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

export async function generate(context: CliGeneratorContext): Promise<void> {
  const { model, defaultOutputPath, pluginOptions } = context
  const outputDir = (pluginOptions.output as string | undefined) ?? defaultOutputPath
  const globalExpose = (pluginOptions.expose as boolean | undefined) ?? true

  const dataModels = model.declarations.filter(isDataModel)

  const modelEntries: string[] = dataModels.map((dm) => {
    const mcpAttr = ModelUtils.getAttribute(dm, '@@mcp')
    let exposed: boolean

    if (mcpAttr) {
      const arg = mcpAttr.args?.[0]
      // Default arg (expose) — if present check its value, else default to true
      if (arg?.value?.$type === 'BooleanLiteral') {
        exposed = (arg.value as { value: boolean }).value
      } else {
        exposed = true
      }
    } else {
      exposed = globalExpose
    }

    return `    ${JSON.stringify(dm.name)}: { exposed: ${exposed} }`
  })

  const code = `// GENERATED by zenstack-mcp — do not edit manually
// Re-run: zenstack generate
import type { McpConfig } from 'zenstack-mcp'

export const mcpConfig: McpConfig = {
  models: {
${modelEntries.join(',\n')}
  }
}
`

  mkdirSync(outputDir, { recursive: true })
  writeFileSync(join(outputDir, 'mcp-config.ts'), code, 'utf8')
}
