import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { SchemaDef } from "@zenstackhq/schema";
import { AllCrudOperations } from "@zenstackhq/orm";
import type { AuthType } from "@zenstackhq/orm";

/**
 * Every CRUD operation the `execute` tool can invoke, sourced directly from
 * ZenStack's `AllCrudOperations`. Using the ORM's own list as the single source
 * of truth means the exposed surface never drifts from the client — adding or
 * renaming an operation in ZenStack is reflected here automatically.
 *
 * Every operation maps to a full-args zod schema from the ORM's own
 * `createQuerySchemaFactory` (see `OPERATION_SCHEMA_METHOD` in
 * `tools/validate.ts`); a new ZenStack operation needs a mapping entry there.
 */
export const ALL_OPERATIONS = AllCrudOperations;
export type McpOperation = (typeof ALL_OPERATIONS)[number];

export interface McpFieldDef {
  name: string;
  type: string;
  isId: boolean;
  isUnique: boolean;
  isRequired: boolean;
  isList: boolean;
  isRelation: boolean;
}

export interface McpModelDef {
  name: string; // 'User' (PascalCase)
  /** lowerFirst(name) — key used to access the model on the ZenStack enhanced client.
   *  @@map does NOT change this: the ZenStack proxy resolves delegates via a
   *  case-insensitive match on schema model names, so lowerFirst(name) is always correct. */
  dbName: string;
  /** Value of @@map(...) if present — the underlying DB table name. Informational only. */
  mapName?: string;
  operations: McpOperation[];
  fields: McpFieldDef[];
  /** Per-model cap on `take` (from `@@mcp(limit: N)`); the effective cap is
   *  min(limit, McpServerConfig.maxTake). */
  limit?: number;
}

/** A single parameter of a custom ZenStack procedure. */
export interface McpProcedureParamDef {
  name: string;
  /** Builtin type or model name (e.g. 'String', 'User'). */
  type: string;
  isList: boolean;
  isRequired: boolean;
}

/** A custom ZenStack procedure (declared with `procedure` / `mutation procedure`). */
export interface McpProcedureDef {
  /** Procedure name (camelCase, as declared in ZModel). */
  name: string;
  params: McpProcedureParamDef[];
  returnType: string;
  returnArray: boolean;
  /** True when declared with the `mutation` keyword (modifies data). */
  mutation: boolean;
}

/** Generated by ZenStack plugin — import from '~/zenstack/mcp-config' */
export interface McpConfig {
  models: Record<
    string,
    {
      exposed: boolean;
      /** Whitelist of operations to expose for this model (default: all operations). */
      operations?: McpOperation[];
      /** Cap on `take` for list reads of this model (from `@@mcp(limit: N)`). */
      limit?: number;
    }
  >;
  /**
   * Custom procedure exposure. A procedure absent from this map (or with
   * `exposed: false`) is hidden from the MCP `procedure` tool. When the whole
   * `procedures` key is omitted, every declared procedure is exposed.
   */
  procedures?: Record<string, { exposed: boolean }>;
}

/** Framework-agnostic request passed to route handlers */
export interface GenericRequest {
  readonly origin: string;
  readonly query: Record<string, string>;
  /** Raw value of the Authorization header (e.g. "Bearer <token>"), if present */
  readonly authorization?: string;
  body(): Promise<Record<string, unknown>>;
}

/** Framework-agnostic response returned by route handlers */
export type GenericResponse =
  | { type: "json"; status?: number; data: unknown }
  | { type: "html"; status?: number; html: string };

export type RouteHandler = (
  req: GenericRequest,
) => GenericResponse | Promise<GenericResponse>;

/** Minimal router interface implemented by each framework adapter */
export interface RouterAdapter {
  get(path: string, handler: RouteHandler): void;
  post(path: string, handler: RouteHandler): void;
}

/** Context passed by transport adapters when validating a Bearer token. */
export interface McpTokenValidationContext {
  /**
   * Origin (`scheme://host[:port]`) the MCP request was received on. Used as
   * the expected token audience (RFC 8707 resource binding) when the adapter
   * has no explicitly configured `resource`.
   */
  origin?: string;
}

/** Common interface for all auth strategies */
export interface McpAuthAdapter {
  /** Mount OAuth 2.0 discovery + token endpoints on a framework-agnostic router */
  mountRoutes(router: RouterAdapter): void;
  /**
   * Validate a Bearer token; return resolved user or throw. `ctx` carries the
   * request origin so implementations can enforce audience (`aud`) binding —
   * rejecting tokens that were minted for a different server.
   */
  validateToken(token: string, ctx?: McpTokenValidationContext): Promise<unknown>;
}

/**
 * Pluggable token store for the built-in OAuth server.
 *
 * The default implementation (`createInMemoryTokenStore`) is in-memory and
 * not suitable for multi-process or serverless deployments. Provide a custom
 * implementation backed by Redis, a database, etc. for production use.
 */
export interface TokenStore {
  /** Persist an authorization code with its PKCE challenge and expiry. */
  saveCode(
    code: string,
    user: unknown,
    codeChallenge: string,
    expiresAt: number,
  ): Promise<void>;
  /**
   * Atomically retrieve and delete an authorization code (one-time use).
   * Returns null if the code does not exist.
   */
  takeCode(code: string): Promise<{
    user: unknown;
    codeChallenge: string;
    expiresAt: number;
  } | null>;
  /** Persist a refresh token with its expiry. */
  saveRefreshToken(
    token: string,
    user: unknown,
    expiresAt: number,
  ): Promise<void>;
  /**
   * Atomically retrieve and delete a refresh token (one-time use / rotation).
   * Returns null if the token does not exist.
   */
  takeRefreshToken(
    token: string,
  ): Promise<{ user: unknown; expiresAt: number } | null>;
  /** Revoke a refresh token without consuming it (e.g. on logout). */
  revokeRefreshToken(token: string): Promise<void>;
}

/** Options for the built-in OAuth strategy */
export interface McpBuiltInAuthOptions {
  /** Called on POST /login to validate credentials; return user object or null */
  validateCredentials: (
    email: string,
    password: string,
  ) => Promise<unknown | null>;
  jwtSecret: string;
  /** Access token TTL in seconds (default: 3600) */
  tokenTtl?: number;
  /** Refresh token TTL in seconds (default: 2592000 = 30 days) */
  refreshTokenTtl?: number;
  /** Custom login page HTML string. The login script is injected automatically before </body>. */
  loginPage?: string | (() => string | Promise<string>);
  /**
   * Custom token store for authorization codes and refresh tokens.
   * Defaults to an in-memory store — not suitable for multi-process or
   * serverless deployments. Provide a Redis- or database-backed store for
   * production.
   */
  tokenStore?: TokenStore;
  /**
   * Pre-shared bearer token required in `Authorization: Bearer <token>` on
   * `POST /register` (RFC 7591 initial access token). When omitted, client
   * registration is open — acceptable only in trusted-network / dev setups.
   * Registered redirect URIs are restricted to HTTPS, plus loopback HTTP for
   * local/native development callbacks.
   */
  initialAccessToken?: string;
  /** Maximum number of OAuth clients that can be registered (default: 100). */
  maxClients?: number;
  /**
   * Canonical resource URI of this MCP server (RFC 8707 resource indicator).
   *
   * Access tokens are minted with this value as their `aud` claim and rejected
   * when presented to a server with a different resource — a token stolen from
   * (or issued for) another service cannot be replayed here, and vice versa.
   * Token requests naming a different `resource` are rejected with
   * `invalid_target`.
   *
   * Defaults to the request origin, which is correct for single-domain
   * deployments. Set explicitly when the server is reachable through several
   * hostnames or behind a proxy that rewrites `Host`.
   */
  resource?: string;
  /**
   * Time-to-live for a registered OAuth client, in seconds (default: 86400 = 24h).
   *
   * Registered clients are evicted once they exceed this TTL. Without it, an open
   * `/register` endpoint (no `initialAccessToken`) lets an unauthenticated caller
   * fill the registry to `maxClients` and permanently lock out new registrations.
   * MCP clients re-register dynamically, so an expired client_id simply triggers a
   * fresh registration.
   */
  clientTtl?: number;
}

/**
 * Minimal structural type expected from a ZenStack v3 client.
 * Used internally by the execute tool — not part of the public API contract.
 */
export type ZenStackClientShape = Record<
  string,
  Record<string, (...args: unknown[]) => Promise<unknown>>
>;

export interface McpServerConfig<Schema extends SchemaDef> {
  /** ZenStack generated schema (import from '~/zenstack/schema') */
  schema: Schema;
  /** Auth adapter or built-in config */
  auth: McpAuthAdapter | McpBuiltInAuthOptions;
  /** Receives the resolved user from the auth adapter; returns ZenStack-enhanced client */
  getClient: (user: AuthType<Schema>) => Promise<unknown>;
  /**
   * Escape hatch to register additional MCP tools on the same server, called
   * after the built-in tools (schema/me/execute/procedure) are registered. Use
   * it to expose host-defined tools (e.g. oRPC-backed) without coupling this
   * package to any RPC framework. Inside a tool handler, read the authenticated
   * caller via the exported `getRequestUser()` (from `zenstack-mcp`), which
   * resolves the per-request user set by the auth/transport layer.
   */
  registerTools?: (server: McpServer) => void;
  /** Exposure config generated by ZenStack plugin (takes priority over include/exclude) */
  mcpConfig?: McpConfig;
  /** Whitelist of model names to expose (used when mcpConfig is absent) */
  include?: string[];
  /** Blacklist of model names to hide (used when mcpConfig is absent) */
  exclude?: string[];
  /**
   * MCP transport to expose (default: "streamable-http").
   *
   * - `"streamable-http"` — stateless (a fresh server per request); the only
   *   serverless-safe option and the only one Express supports.
   * - `"sse"` / `"both"` — keeps SSE sessions in a per-instance in-memory map, so
   *   a follow-up message routed to a different instance fails with "unknown
   *   session". **Only use SSE on a single-instance deployment** (not Cloudflare
   *   Workers, Lambda, or any autoscaled/multi-replica host).
   */
  transport?: "streamable-http" | "sse" | "both";
  /** MCP server name reported to clients (default: "zenstack-mcp") */
  name?: string;
  /** MCP server version reported to clients (default: package version) */
  version?: string;
  /**
   * Per-model operation whitelist. Restricts which operations the MCP tools
   * advertise and enforce for each model. When omitted, all operations are
   * available for every exposed model.
   *
   * Takes precedence over `mcpConfig.models[name].operations`.
   *
   * @example
   * modelOperations: {
   *   Post: ['findMany', 'findUnique', 'create'],  // read + create only
   *   User: ['findMany', 'findUnique'],             // read-only
   * }
   */
  modelOperations?: Record<string, McpOperation[]>;
  /**
   * When `true`, `deleteMany` and `updateMany` calls with an absent or empty
   * `where` are rejected before reaching the database. Prevents an LLM from
   * accidentally wiping or overwriting entire tables.
   *
   * Defaults to `false`. Enable explicitly in production.
   */
  requireWhereForBulk?: boolean;
  /**
   * Maximum relation-nesting depth accepted in operation args (where/select/
   * include/data). Passed to the ORM's query schema factory; args nesting
   * deeper than this are rejected at validation time. Keeping it low also
   * keeps the JSON schemas returned by the `schema` tool small enough for LLM
   * context windows.
   *
   * Defaults to `2`. Set to `Infinity` for unlimited depth (the ORM default).
   */
  relationDepth?: number;
  /**
   * Global cap on `take` for list reads (`findMany`, `findFirst`, …). A call
   * with `take` above the cap is rejected. Per-model `@@mcp(limit: N)` caps
   * combine with this via `min`. When omitted, only per-model limits apply.
   */
  maxTake?: number;
  /**
   * Browser-origin allowlist for the MCP endpoint, guarding against DNS-rebinding
   * attacks (a malicious web page driving a localhost/private MCP server from the
   * victim's browser), as recommended by the MCP Streamable HTTP transport spec.
   *
   * Requests that carry an `Origin` header not in this list are rejected with 403.
   * Requests with **no** `Origin` header are allowed — native MCP clients (Claude
   * Desktop, CLIs) don't send one; only browsers do. Provide a predicate for
   * dynamic matching.
   *
   * When omitted, no Origin check is performed (backward compatible).
   *
   * @example allowedOrigins: ['https://claude.ai']
   */
  allowedOrigins?: string[] | ((origin: string) => boolean);
}
