import type { SchemaDef } from "@zenstackhq/schema";
import type { AuthType } from "@zenstackhq/orm";

export type McpOperation =
  | "findMany"
  | "findUnique"
  | "findFirst"
  | "create"
  | "createMany"
  | "update"
  | "updateMany"
  | "upsert"
  | "delete"
  | "deleteMany"
  | "count";

export const ALL_OPERATIONS: McpOperation[] = [
  "findMany",
  "findUnique",
  "findFirst",
  "create",
  "createMany",
  "update",
  "updateMany",
  "upsert",
  "delete",
  "deleteMany",
  "count",
];
// Compile-time guard: fails if ALL_OPERATIONS drifts from McpOperation union
const _opCheck: McpOperation[] = ALL_OPERATIONS;

export interface McpFieldDef {
  name: string;
  type: string;
  isId: boolean;
  isRequired: boolean;
  isList: boolean;
  isRelation: boolean;
}

export interface McpModelDef {
  name: string; // 'User' (PascalCase)
  /** lowerFirst(name) — key used to access the model on the ZenStack enhanced client.
   *  @@map does NOT change this: the ZenStack proxy resolves delegates via a
   *  case-insensitive match on schema model names, so lowerFirst(name) is always correct. */
  dbName: string;
  /** Value of @@map(...) if present — the underlying DB table name. Informational only. */
  mapName?: string;
  operations: McpOperation[];
  fields: McpFieldDef[];
}

/** Generated by ZenStack plugin — import from '~/zenstack/mcp-config' */
export interface McpConfig {
  models: Record<string, {
    exposed: boolean;
    /** Whitelist of operations to expose for this model (default: all operations). */
    operations?: McpOperation[];
  }>;
}

/** Framework-agnostic request passed to route handlers */
export interface GenericRequest {
  readonly origin: string;
  readonly query: Record<string, string>;
  /** Raw value of the Authorization header (e.g. "Bearer <token>"), if present */
  readonly authorization?: string;
  body(): Promise<Record<string, unknown>>;
}

/** Framework-agnostic response returned by route handlers */
export type GenericResponse =
  | { type: "json"; status?: number; data: unknown }
  | { type: "html"; status?: number; html: string };

export type RouteHandler = (
  req: GenericRequest,
) => GenericResponse | Promise<GenericResponse>;

/** Minimal router interface implemented by each framework adapter */
export interface RouterAdapter {
  get(path: string, handler: RouteHandler): void;
  post(path: string, handler: RouteHandler): void;
}

/** Common interface for all auth strategies */
export interface McpAuthAdapter {
  /** Mount OAuth 2.0 discovery + token endpoints on a framework-agnostic router */
  mountRoutes(router: RouterAdapter): void;
  /** Validate a Bearer token; return resolved user or throw */
  validateToken(token: string): Promise<unknown>;
}

/**
 * Pluggable token store for the built-in OAuth server.
 *
 * The default implementation (`createInMemoryTokenStore`) is in-memory and
 * not suitable for multi-process or serverless deployments. Provide a custom
 * implementation backed by Redis, a database, etc. for production use.
 */
export interface TokenStore {
  /** Persist an authorization code with its PKCE challenge and expiry. */
  saveCode(
    code: string,
    user: unknown,
    codeChallenge: string,
    expiresAt: number,
  ): Promise<void>;
  /**
   * Atomically retrieve and delete an authorization code (one-time use).
   * Returns null if the code does not exist.
   */
  takeCode(
    code: string,
  ): Promise<{ user: unknown; codeChallenge: string; expiresAt: number } | null>;
  /** Persist a refresh token with its expiry. */
  saveRefreshToken(
    token: string,
    user: unknown,
    expiresAt: number,
  ): Promise<void>;
  /**
   * Atomically retrieve and delete a refresh token (one-time use / rotation).
   * Returns null if the token does not exist.
   */
  takeRefreshToken(
    token: string,
  ): Promise<{ user: unknown; expiresAt: number } | null>;
  /** Revoke a refresh token without consuming it (e.g. on logout). */
  revokeRefreshToken(token: string): Promise<void>;
}

/** Options for the built-in OAuth strategy */
export interface McpBuiltInAuthOptions {
  /** Called on POST /login to validate credentials; return user object or null */
  validateCredentials: (
    email: string,
    password: string,
  ) => Promise<unknown | null>;
  jwtSecret: string;
  /** Access token TTL in seconds (default: 3600) */
  tokenTtl?: number;
  /** Refresh token TTL in seconds (default: 2592000 = 30 days) */
  refreshTokenTtl?: number;
  /** Custom login page HTML string. The login script is injected automatically before </body>. */
  loginPage?: string | (() => string | Promise<string>);
  /**
   * Custom token store for authorization codes and refresh tokens.
   * Defaults to an in-memory store — not suitable for multi-process or
   * serverless deployments. Provide a Redis- or database-backed store for
   * production.
   */
  tokenStore?: TokenStore;
  /**
   * Pre-shared bearer token required in `Authorization: Bearer <token>` on
   * `POST /register` (RFC 7591 initial access token). When omitted, client
   * registration is open — acceptable only in trusted-network / dev setups.
   */
  initialAccessToken?: string;
  /** Maximum number of OAuth clients that can be registered (default: 100). */
  maxClients?: number;
}

/**
 * Minimal structural type expected from a ZenStack v3 client.
 * Used internally by the execute tool — not part of the public API contract.
 */
export type ZenStackClientShape = Record<
  string,
  Record<string, (...args: unknown[]) => Promise<unknown>>
>;

export interface McpServerOptions<Schema extends SchemaDef> {
  /** ZenStack generated schema (import from '~/zenstack/schema') */
  schema: Schema;
  /** Auth adapter or built-in config */
  auth: McpAuthAdapter | McpBuiltInAuthOptions;
  /** Receives the resolved user from the auth adapter; returns ZenStack-enhanced client */
  getClient: (user: AuthType<Schema>) => Promise<unknown>;
  /** Exposure config generated by ZenStack plugin (takes priority over include/exclude) */
  mcpConfig?: McpConfig;
  /** Whitelist of model names to expose (used when mcpConfig is absent) */
  include?: string[];
  /** Blacklist of model names to hide (used when mcpConfig is absent) */
  exclude?: string[];
  /** MCP transport to expose (default: "streamable-http"). Express only supports "streamable-http". */
  transport?: "streamable-http" | "sse" | "both";
  /** MCP server name reported to clients (default: "zenstack-mcp") */
  name?: string;
  /** MCP server version reported to clients (default: package version) */
  version?: string;
  /**
   * Per-model operation whitelist. Restricts which operations the MCP tools
   * advertise and enforce for each model. When omitted, all operations are
   * available for every exposed model.
   *
   * Takes precedence over `mcpConfig.models[name].operations`.
   *
   * @example
   * modelOperations: {
   *   Post: ['findMany', 'findUnique', 'create'],  // read + create only
   *   User: ['findMany', 'findUnique'],             // read-only
   * }
   */
  modelOperations?: Record<string, McpOperation[]>;
  /**
   * When `true`, `deleteMany` and `updateMany` calls with an absent or empty
   * `where` are rejected before reaching the database. Prevents an LLM from
   * accidentally wiping or overwriting entire tables.
   *
   * Defaults to `false`. Enable explicitly in production.
   */
  requireWhereForBulk?: boolean;
}
