/**
 * Example: Hono + better-auth + ZenStack v3 + SQLite
 *
 * Run first:
 *   bun run db:generate   # zen generate → .zenstack/
 *   bun run db:push       # push schema to dev.db (creates all tables)
 *   bun dev
 */
import { Hono } from "hono";
import { PolicyPlugin } from "@zenstackhq/plugin-policy";
import { createHonoMcpHandler } from "zenstack-mcp/server-adapters/hono";
import { betterAuthMcpAdapter } from "zenstack-mcp/auth-adapters/better-auth";
import { auth } from "./auth";

// These files are generated by `bun run db:generate` (zen generate).
// TypeScript will complain until the first generation — that's expected.
import { schema } from "./zenstack/schema";
import { mcpConfig } from "./zenstack/mcp-config";
import { db } from "./db";
import type { AuthType } from "@zenstackhq/orm";

// ── Hono app ──────────────────────────────────────────────────────────────────
const app = new Hono();

// better-auth's own HTTP routes (sign-in, sign-up, session, OAuth callbacks…)
app.on(["GET", "POST"], "/api/auth/**", (c) => auth.handler(c.req.raw));

app.get("/health", (c) => c.json({ ok: true }));

// createHonoMcpHandler returns two separate apps:
//   oauthRoutes   — mount at root so OAuth discovery is at /.well-known/...
//   mcpMiddleware — mount wherever you want the MCP endpoint (here: root)
const { oauthRoutes, mcpMiddleware } = createHonoMcpHandler({
  schema,
  mcpConfig, // hides Session, Account, Verification (@@mcp(false) in schema.zmodel)
  auth: betterAuthMcpAdapter(auth, {
    loginPage: () => Bun.file(import.meta.dir + "/login.html").text(),
  }),
  getClient: async (user: AuthType<typeof schema>) =>
    db.$use(new PolicyPlugin()).$setAuth({ id: user.id }),
});

app.route("/", oauthRoutes); // OAuth at root (required by MCP spec)
app.route("/", mcpMiddleware); // MCP transport at root (move to /mcp if desired)

Bun.serve({ port: 3000, fetch: app.fetch });

console.log("MCP server       → http://localhost:3000");
console.log("better-auth API  → http://localhost:3000/api/auth");
console.log(
  "OAuth discovery  → http://localhost:3000/.well-known/oauth-authorization-server",
);
console.log("MCP (HTTP)       → POST http://localhost:3000/");
console.log("MCP (SSE)        → GET  http://localhost:3000/sse");

console.log();
console.log("Demo login       → http://localhost:3000/login");
console.log("Test credentials → alice@example.com / alice1234");
console.log("                   bob@example.com   / bob12345");
console.log("                   carol@example.com / carol123");
