/// <reference types="@cloudflare/workers-types" />
import { McpAgent } from "agents/mcp";
import OAuthProvider, {
  type OAuthProviderOptions,
} from "@cloudflare/workers-oauth-provider";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { SchemaDef } from "@zenstackhq/schema";
import type { AuthType } from "@zenstackhq/orm";
import { buildMcpServer, extractModels } from "../server.js";
import {
  bridgeModelMutations,
  registerModelResources,
} from "../events/notifications.js";
import type {
  McpConfig,
  McpOperation,
  McpServerConfig,
  MutationPublisher,
} from "../types.js";

/**
 * Options for {@link createZenStackMcpAgent}.
 *
 * Unlike the Hono/Express adapters, the Workers adapter does **not** take a
 * zenstack-mcp `auth` adapter: on Cloudflare, `@cloudflare/workers-oauth-provider`
 * authenticates the request before it reaches the Durable Object and hands the
 * grant down as `props`. Map those props to a user with {@link resolveUser}.
 */
export interface WorkersMcpAgentOptions<
  Schema extends SchemaDef,
  Props extends Record<string, unknown> = Record<string, unknown>,
> {
  /** ZenStack generated schema (import from '~/zenstack/schema'). */
  schema: Schema;
  /** Receives the resolved user; returns the ZenStack-enhanced client. */
  getClient: (user: AuthType<Schema>) => Promise<unknown>;
  /**
   * Maps the OAuth grant props (set by `@cloudflare/workers-oauth-provider`) to
   * the user passed to {@link getClient}. The Durable Object has no per-request
   * AsyncLocalStorage context, so the user is resolved from `props` instead.
   */
  resolveUser: (props: Props) => AuthType<Schema> | Promise<AuthType<Schema>>;
  /** Exposure config generated by the ZenStack plugin. */
  mcpConfig?: McpConfig;
  /** Whitelist of model names to expose (used when mcpConfig is absent). */
  include?: string[];
  /** Blacklist of model names to hide (used when mcpConfig is absent). */
  exclude?: string[];
  /** Per-model operation whitelist. */
  modelOperations?: Record<string, McpOperation[]>;
  /** Reject bulk delete/update without a `where` clause. */
  requireWhereForBulk?: boolean;
  /** MCP server name reported to clients. */
  name?: string;
  /** MCP server version reported to clients. */
  version?: string;
  /**
   * Single source of truth publisher (e.g. your `PublisherDurableObject`). When
   * set, the `execute` tool publishes mutations and — with
   * {@link resourceNotifications} — the agent pushes `resources/updated`.
   */
  publisher?: MutationPublisher;
  /** Maps a model name to its publish channel (default `model.toLowerCase()`). */
  channelFormatter?: (modelName: string) => string;
  /**
   * Expose models as subscribable MCP resources and push
   * `notifications/resources/updated` on mutations. Requires {@link publisher}.
   * Defaults to `true` when a publisher is provided.
   */
  resourceNotifications?: boolean;
}

/**
 * The Durable Object class returned by {@link createZenStackMcpAgent}: an
 * `McpAgent` constructor plus its static `serve`/`serveSSE`/`mount` mounters.
 * Declared explicitly so the package's generated types stay portable (the
 * inferred anonymous subclass would leak internal `agents` types).
 */
export interface ZenStackMcpAgentClass<
  Env extends Cloudflare.Env,
  Props extends Record<string, unknown>,
> {
  new (...args: unknown[]): McpAgent<Env, unknown, Props>;
  serve: typeof McpAgent.serve;
  serveSSE: typeof McpAgent.serveSSE;
  mount: typeof McpAgent.mount;
}

/**
 * Builds a Cloudflare `McpAgent` (Durable Object) class wired to a ZenStack MCP
 * server. The Durable Object owns one MCP session — its streamable-HTTP stream,
 * resource subscriptions, and (with a publisher) server→client notifications.
 *
 * Bind the returned class as a Durable Object in `wrangler` and mount it with
 * `YourAgent.serve("/mcp", { binding: "MCP_OBJECT" })`, or use
 * {@link createWorkersMcpHandler} to also wire OAuth.
 *
 * @example
 * ```ts
 * export const ZenStackMcp = createZenStackMcpAgent({
 *   schema, getClient,
 *   resolveUser: (props) => props.user as AuthType<typeof schema>,
 *   publisher: env.PUBLISHER, // your Durable-Object-backed publisher
 * });
 * export default ZenStackMcp.serve("/mcp", { binding: "ZEN_STACK_MCP" });
 * ```
 */
export function createZenStackMcpAgent<
  Schema extends SchemaDef,
  Env extends Cloudflare.Env = Cloudflare.Env,
  Props extends Record<string, unknown> = Record<string, unknown>,
>(
  options: WorkersMcpAgentOptions<Schema, Props>,
): ZenStackMcpAgentClass<Env, Props> {
  const {
    resolveUser,
    publisher,
    channelFormatter,
    resourceNotifications,
    getClient,
    ...rest
  } = options;

  const enableNotifications =
    (resourceNotifications ?? true) && publisher !== undefined;

  class ZenStackMcpAgent extends McpAgent<Env, unknown, Props> {
    server!: McpServer;

    async init(): Promise<void> {
      // getClient resolves the user lazily from the OAuth props at call time.
      // The execute tool / resource reads call getClient(getRequestUser()); here
      // getRequestUser() is undefined (no ALS in the DO), so we ignore the
      // argument and resolve from this.props — one user per session.
      const boundConfig = {
        ...rest,
        getClient: async () =>
          getClient(await resolveUser((this.props ?? {}) as Props)),
        publisher,
        channelFormatter,
      } as unknown as McpServerConfig<Schema>;

      const models = extractModels<Schema>(boundConfig);
      const server = buildMcpServer<Schema>(models, boundConfig);

      if (enableNotifications && publisher) {
        registerModelResources(server, models, boundConfig.getClient);
        bridgeModelMutations(server, models, publisher, { channelFormatter });
      }

      this.server = server;
    }
  }

  // Cast through unknown: the concrete subclass's constructor params (AgentContext,
  // Env) are narrower than the portable `(...args: unknown[])` signature, but the
  // Cloudflare runtime always instantiates it with the right arguments.
  return ZenStackMcpAgent as unknown as ZenStackMcpAgentClass<Env, Props>;
}

/**
 * Options for {@link createWorkersMcpHandler}: agent options plus the OAuth
 * wiring handled by `@cloudflare/workers-oauth-provider`.
 */
export interface WorkersMcpHandlerOptions<
  Schema extends SchemaDef,
  Props extends Record<string, unknown> = Record<string, unknown>,
> extends WorkersMcpAgentOptions<Schema, Props> {
  /** MCP endpoint path (default `"/mcp"`). */
  path?: string;
  /**
   * Durable Object binding name for the agent — must match the `wrangler`
   * `durable_objects` binding that points at the returned `Agent` class.
   */
  binding: string;
  /**
   * Your login/consent handler (an `{ fetch }` worker). It authenticates the
   * user and completes the authorization, attaching `props` consumed by
   * {@link WorkersMcpAgentOptions.resolveUser}. This is app-specific — e.g. a
   * Better Auth–backed login page.
   */
  defaultHandler: ExportedHandler<Cloudflare.Env>;
  /** OAuth authorize endpoint (default `"/oauth/authorize"`). */
  authorizeEndpoint?: string;
  /** OAuth token endpoint (default `"/oauth/token"`). */
  tokenEndpoint?: string;
  /** Dynamic client registration endpoint (default `"/oauth/register"`). */
  clientRegistrationEndpoint?: string;
  /** Advertised OAuth scopes. */
  scopesSupported?: string[];
}

/**
 * Wires {@link createZenStackMcpAgent} behind an `OAuthProvider`, returning the
 * worker default export (`handler`) and the Durable Object class (`Agent`) to
 * bind in `wrangler`.
 *
 * @example
 * ```ts
 * const { handler, Agent } = createWorkersMcpHandler({
 *   schema, getClient,
 *   resolveUser: (props) => props.user as AuthType<typeof schema>,
 *   publisher: env.PUBLISHER,
 *   binding: "ZEN_STACK_MCP",
 *   defaultHandler: loginHandler, // your Better Auth login UI
 * });
 * export { Agent as ZEN_STACK_MCP };
 * export default handler;
 * ```
 */
export function createWorkersMcpHandler<
  Schema extends SchemaDef,
  Props extends Record<string, unknown> = Record<string, unknown>,
>(options: WorkersMcpHandlerOptions<Schema, Props>) {
  const path = options.path ?? "/mcp";
  const Agent = createZenStackMcpAgent<Schema, Cloudflare.Env, Props>(options);

  const handler = new OAuthProvider({
    apiRoute: path,
    // Agent.serve returns an `{ fetch }` worker matching apiHandler's shape.
    apiHandler: Agent.serve(path, {
      binding: options.binding,
    }) as unknown as NonNullable<
      OAuthProviderOptions<Cloudflare.Env>["apiHandler"]
    >,
    defaultHandler: options.defaultHandler,
    authorizeEndpoint: options.authorizeEndpoint ?? "/oauth/authorize",
    tokenEndpoint: options.tokenEndpoint ?? "/oauth/token",
    clientRegistrationEndpoint:
      options.clientRegistrationEndpoint ?? "/oauth/register",
    ...(options.scopesSupported
      ? { scopesSupported: options.scopesSupported }
      : {}),
  });

  return { handler, Agent };
}
