/**
 * Example: Express + built-in OAuth + ZenStack v3 + SQLite
 *
 * Run first:
 *   bun run db:generate   # zen generate → zenstack/schema.ts + zenstack/mcp-config.ts
 *   bun run db:push       # push schema to dev.db (creates all tables)
 *   bun run db:seed       # populate 3 users + 4 posts
 *   bun dev
 */
import express from "express";
import bcrypt from "bcryptjs";
import { PolicyPlugin } from "@zenstackhq/plugin-policy";
import { createExpressMcpHandler } from "zenstack-mcp/server-adapters/express";
import { createSqliteTokenStore } from "./token-store";

// These files are generated by `bun run db:generate` (zen generate).
// TypeScript will complain until the first generation — that's expected.
import { schema } from "./zenstack/schema";
import { mcpConfig } from "./zenstack/mcp-config";
import { db } from "./db";
import type { AuthType } from "@zenstackhq/orm";

// Persistent SQLite-backed token store — survives restarts, safe for multi-process.
// Swap for a Redis implementation to scale across multiple machines.
const tokenStore = createSqliteTokenStore(process.env.DB_PATH ?? "./dev.db");

// ── App ──────────────────────────────────────────────────────────────────────
const app = express();

// createExpressMcpHandler returns two separate routers:
//   oauthRoutes   — mount at root so OAuth discovery is at /.well-known/...
//   mcpMiddleware — mount wherever you want the MCP endpoint (here: root)
//
// OAuth endpoints (at root):
//   GET  /.well-known/oauth-authorization-server
//   GET  /.well-known/oauth-protected-resource
//   GET  /oauth/authorize   → login page
//   POST /login             → credential validation
//   POST /oauth/token       → PKCE code exchange → JWT access token
//   POST /oauth/revoke      → refresh token revocation
//
// MCP endpoint:
//   POST /                  → MCP streamable-HTTP (requires Authorization: Bearer <token>)
const { oauthRoutes, mcpMiddleware } = createExpressMcpHandler({
  schema,
  mcpConfig,
  auth: {
    validateCredentials: async (email: string, password: string) => {
      const user = await db.user.findUnique({
        where: { email },
        select: { id: true, email: true, passwordHash: true },
      });
      if (!user) return null;
      const ok = await bcrypt.compare(password, user.passwordHash);
      return ok ? { id: user.id, email: user.email } : null;
    },
    jwtSecret: process.env.JWT_SECRET ?? "change-me-in-production",
    tokenTtl: 3600,
    loginPage: () => Bun.file(import.meta.dir + "/login.html").text(),
    tokenStore,
  },
  // PolicyPlugin enforces @@allow / @@deny from schema.zmodel.
  getClient: async (user: AuthType<typeof schema>) =>
    db.$use(new PolicyPlugin()).$setAuth({ id: user.id }),
});

app.use(oauthRoutes); // OAuth at root (required by MCP spec)
app.use("/", mcpMiddleware); // MCP transport at root (move to /mcp if desired)

app.get("/health", (_req, res) => res.json({ ok: true }));

app.listen(3001, () => {
  console.log("Express + built-in auth MCP server → http://localhost:3001");
  console.log(
    "Discovery: GET  http://localhost:3001/.well-known/oauth-authorization-server",
  );
  console.log(
    "MCP (HTTP): POST http://localhost:3001/ (requires Authorization: Bearer <token>)",
  );
  console.log();
  console.log("Test credentials: alice@example.com / alice1234");
  console.log("                  bob@example.com   / bob12345");
  console.log("                  carol@example.com / carol123");
});
